name: flutter_woocommerce
description: A woocommerce mobile app.
publish_to: 'none'
version: 2.0.2+2

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  get: ^4.6.5
  intl: ^0.17.0
  http: ^0.13.4
  shared_preferences: ^2.0.15
  connectivity_plus: ^2.3.6
  firebase_core: ^2.5.0
  firebase_messaging: ^14.2.2
  flutter_local_notifications: ^9.7.0
  path_provider: ^2.0.11
  url_strategy: ^0.2.0
  cached_network_image: ^3.2.1
  image_picker: ^0.8.5+3
  shimmer_animation: ^2.1.0+1
  #local_auth: ^2.1.0
  url_launcher: ^6.1.5
  pull_to_refresh: ^2.0.0
  convex_bottom_bar: ^3.0.0
  photo_view: ^0.14.0
  flutter_html:
  flutter_widget_from_html: ^0.8.5
  #fwfh_selectable_text: ^0.8.3+1
  image_compression_flutter: ^1.0.2
  universal_html: ^2.0.8
  #fwfh_webview: ^0.6.2+1
  fwfh_text_style: ^2.22.8+1

  ## Payment gateways
  # flutter_paypal: ^0.0.8
  flutter_stripe: ^3.2.0
  razorpay_flutter: ^1.3.4
  flutter_paystack: ^1.0.7

  paytm_allinonesdk: ^1.1.7
  flutterwave_standard: ^1.0.7
  rate_my_app: ^1.1.3
  google_maps_flutter: ^2.2.1
  geolocator: ^9.0.2
  flutter_typeahead: ^4.1.1
  geocoding: ^2.0.4
  geocode: 1.0.2
  #dependencies:
  share_plus: ^5.0.0
  firebase_dynamic_links: ^5.0.12
  firebase_analytics: ^10.1.1
  carousel_slider: ^4.0.0
  card_swiper: ^2.0.4
  dotted_border: ^2.0.0+3
  string_to_color: ^2.0.0
  pin_code_fields: ^7.3.0
  get_storage: ^2.1.1


dependency_overrides:
  modal_bottom_sheet:
    git:
      url: https://github.com/danReynolds/modal_bottom_sheet.git
      path: modal_bottom_sheet


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/image/
    - assets/language/
    - assets/config/
    - assets/country_state/

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/font/Roboto-Regular.ttf
          weight: 400
        - asset: assets/font/Roboto-Medium.ttf
          weight: 500
        - asset: assets/font/Roboto-Bold.ttf
          weight: 700
        - asset: assets/font/Roboto-Black.ttf
          weight: 900

    - family: Poppins
      fonts:
        - asset: assets/font/Poppins-Regular.ttf
          weight: 400
        - asset: assets/font/Poppins-Medium.ttf
          weight: 500
        - asset: assets/font/Poppins-Bold.ttf
          weight: 700
        - asset: assets/font/Poppins-Black.ttf
          weight: 900

    - family: DMSans
      fonts:
        - asset: assets/font/DMSans-Regular.ttf
          weight: 400
        - asset: assets/font/DMSans-Medium.ttf
          weight: 500
        - asset: assets/font/DMSans-Bold.ttf
          weight: 900